name: Android CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v6

      # Set up Java 8 (Temurin)
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'

      # Make Gradle wrapper executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # Run Android lint
      - name: Run Android lint
        run: ./gradlew lint --stacktrace

      # Upload APK artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/**/*.apk
